development:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: dota
 pool: 5
 username: bachthinh
 password: tokyo092015
 host: btdevelop.c8wcfu2k8zwk.us-west-2.rds.amazonaws.com
 port: 3306